### ISSUE TITLE
けいたさんが作成したプロジェクトがPLAYできない

### ISSUE THREAD

**Issue by okimaho** [fabnavi/Fabnavi4#23]
WIndowsのスティックPC使用

**Comment by zigen** [comment]
public/privateのような権限の問題ですか？別の問題ですか？

**Comment by okimaho** [comment]
すみません、権限の問題でした。けいたさんでログインして確認しなおすと、無事表示することができました。
ただ、8枚撮影したはずが、2枚しか保存されていませんでした。
スティックPCで今度は沖アカウントでCreateNewProjectして写真たくさん撮ったのですが、今度はサムネイルすら表示されません…
