### ISSUE TITLE
はじめからフルスクリーンにしてほしい

### ISSUE THREAD

**Issue by okimaho** [fabnavi/Fabnavi4#33]
CreateNewProjectの後のキャリブレーションの撮影時に、フルスクリーンになる前に紙の十字線を合わせてしまったりして混乱するので、もうできるだけ早い段階（CreateNewProjectのタイトル決める画面とか）でフルスクリーンにしておいてほしいです。

**Comment by zigen** [comment]
"NOTE: Fullscreen requests need to be called from within an event handler or otherwise they will be denied." とのことで、現状のページ遷移を伴う形では、常にフルスクリーンにできません。 
https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Using_full_screen_mode

解決策としては
- シングルページにする
-  FullscreenAddonのようもので対処する
-  フルスクリーンを諦める

**Comment by okimaho** [comment]
なるほどです。

【現状の問題】
CreateNewProject直後の画面A：　https://gyazo.com/030be1ff155fccf5831b224eea885cdd
でエンターを押すと、「フルスクリーンになる」のと「写真を撮る」のが同時に行われる→十字線の位置がずれたままで写真が撮影されてしまうという問題がある。

【改善案】
- 画面Aをフルスクリーンで表示する（これでもページ遷移問題になるのでしょうか？？）
- 画面Aでエンターを押すと写真は撮らずに「フルスクリーンになる」だけを行う。（その後、フルスクリーンになった状態でエンターを押す→写真を撮る、ようにする）

**Comment by zigen** [comment]
enterでfullscreenと撮影のどちらかだけにするようにしました
