### ISSUE TITLE
TOPページのメニューは常に表示していてほしい

### ISSUE THREAD

**Issue by okimaho** [fabnavi/Fabnavi4#35]
TOPページのメニューアイコン（一番上にあるTOP／MyProject／Createなど）を押すと、少し下の位置（メッセージ表示場所）に移動するのでメニューが見えなくなり、操作しにくい。いつでもメニューにアクセスできるように、普通に表示して頂きたいです。

**Comment by zigen** [comment]
固定しました

**Comment by okimaho** [comment]
すみません、プロジェクトの位置がずれて表示されます
https://gyazo.com/7c487608aea0a17310c0bbc2b92b402e

**Comment by zigen** [comment]
調性しました
