### ISSUE TITLE
TOPでプロジェクトのPLAYを選択したときに、次の画面に移動するまでにサムネイルが表示されるのを修正

### ISSUE THREAD

**Issue by okimaho** [fabnavi/Fabnavi4#37]
すぐ遷移してくれると気にならないのだけれど、通信が遅いと長時間サムネイルを見続けることになり、正しく動いていないのではないかという不安な気持ちになる。
なので、下記どちらかの対応をするとよいかと思いました。
- サムネイルを表示しないようにする
- 「Now Loading」等の文字を表示する

**Comment by zigen** [comment]
弊害しかなさそうなので非表示にしました
