### ISSUE TITLE
「You need to sign in」のメッセージを出す代わりに、直接サインインページに飛ばす

### ISSUE THREAD

**Issue by okimaho** [fabnavi/Fabnavi4#8]
- MyProjectをクリックしたとき
- TOPページのプロジェクトを編集（Edit/Record/Delete)しようとしたとき

に、エラーメッセージが表示されていることに最初の数回気付けず、なぜ操作ができないのかわからなかったため

**Comment by zigen** [comment]
personaひらく

**Comment by zigen** [comment]
ひらくようにした
